### ISSUE TITLE
How can I read N records at a time?

### ISSUE THREAD

**Issue by dandv** [wdavidw/node-csv#102]
I'm trying to parse the records in a CSV file one by one (those records are sent to the client for display, on request). How should that be done?

I tried using `pause()` on the object returned by `csv()`, but it seemed that the buffers were large and reading individual records wasn't possible. An example would be great.

A `next(N)` method would also be very useful.

Here's what I've tried:

    var handle = csv();
    handle
      .from("example.csv", { columns: true })
      .pause();
      
    handle
      .on("record", function (d) {
        console.log(d);  // all 10 records in example.csv are output
        handle.pause();
      })
      .on("end", function () {
        console.log("done");  // doesn't get displayed if a pause() method is called
      })

**Comment by chacliff** [comment]
is this being maintained, this still doesn't appear to be working and the issue is still open i'm doing something similar but its not working with pipes or based on the stream example

**Comment by wdavidw** [comment]
this issue shall be close, you'll need to either write your own implementation of stream.Transform, use an existing one (i provide stream-transform if u wish to try it).

**Comment by chacliff** [comment]
whats the point of doing a .transform if you aren't even providing it, it might as well be removed as functionality if it doesn't do what we expect it to or you intend by the examples or the functionality.

**Comment by wdavidw** [comment]
the code from this issue is using a legacy api no longer supported. look at the [docs](http://csv.adaltas.com), the tests or [this sample](https://github.com/wdavidw/node-csv/blob/master/samples/pipe.js) so see how to use transform

**Comment by housseynCheriet** [comment]
### Try select-csv: It converts .csv files into an array and even into lines.
[Github](https://github.com/housseynCheriet/select-csv)

```
 const { parseCsv } = require("select-csv");
    
    // First create object from .csv file
    const parse = parseCsv('file_path.csv');
    
    var result;
    // Use this
    result = parse.chunk(1000)
    // Or use this
    result = parse.rowOffset(0, 1000)
```
