### ISSUE TITLE
Sample Request: Adding Records and Streaming Output

### ISSUE THREAD

**Issue by jdarling** [wdavidw/node-csv#130]
I've read through the documentation and the sample.  They all seem to focus on having something to start with and doing everything in one big block.

This is fine and dandy if you have a small number of records, but when you have a large number of records or your records are streamed into the application a few at a time, how would you setup an output stream and add records to it.

Specifically using HTTP (express.js in this case but should work for any) to serve up a download of a table.

Ideally a sample that shows something as follows:
  1) Init a new CSV object for download
  2) Tie the response stream to the CSV output stream
  3) Start adding in records a block at a time (say 10 or so)
  4) Once all records are added close the stream

It would be easy to simulate 3 with a setTimeout() call that generates x records and then if # of iterations is < goal call itself.  If # of iterations is >= goal, then close the stream (note > should never happen, but hey its a safe catch)

If this is an outlandish request, just give me some pointers and I'll do it and post back here the results.  But right now, I'm stuck even on where to start.

**Comment by wdavidw** [comment]
All the csv function a stream based. you're right, callback style approach is only for conveniency. closing.
