### ISSUE TITLE
Unable to Perform Multiple Transforms

### ISSUE THREAD

**Issue by bitmage** [wdavidw/node-csv#134]
I'm trying to do this:

``` javascript
fs.createReadStream(fileName, 'utf8').pipe(csv()).transform(processRow).transform(mergeData).transform(createRecord)
```

I would expect the second and third transform calls to receive the data from the previous step.  However, each one seems get the original data.

Is there a way to accomplish a processing pipeline like this?  I need the data in object format, so pipe() doesn't work... that runs it through the stringifier.  The whole point of this is to save the records into Mongo, so I need to go from CSV -> Objects -> Record Inserts.

**Comment by wdavidw** [comment]
This functionnality is delegated to other module like @vpArth mentionned. closing.
