### ISSUE TITLE
Row delimiter not issued after row output.

### ISSUE THREAD

**Issue by squareproton** [wdavidw/node-csv#167]
I've noticed that the row stringifier logic only writes a row delimiter when it receives a new row. Your flow at the moment produces a implode() like output. That is to say, if you have n > 0 rows you'll output n-1 row delimiters.

The problem with this is pretty much all csv parsers - including node-csv - when consuming a csv stream require the row delimiter in order to trigger the 'record' event. For n rows there needs to be n row delimiters. I've run into this whilst piping the csv output produced by node-csv into a node-csv's stream reader. Basically the most recently produced row wasn't handled until another came in (with it's leading row delimiter) so everything was lagged by one.

It looks like there's another related issue; https://github.com/wdavidw/node-csv/issues/157 . The fix for both would be to always put the row delimiter at the end of each newly generated row.

My diff for stringify.js is 

```
93c93
<     newLine = this.csv.state.countWriten ? this.csv.options.to.rowDelimiter || "\n" : '';z

---
>     newLine = '';
128a129
> 
130c131
<     line = newLine;

---
>     line = newLine + this.csv.options.to.rowDelimiter || "\n";
```

Sorry I've not yet figured out how to do pull request.

My test case code went something like.

producer.js

```
var csv = require('csv');
var out = csv().to(process.stdout);
var cnt = 0;
setInterval(function(){
    out.write([cnt++, new Date().getTime(), {}]);
}, 1000);
```

consumer.js

```
var csv = require('csv')();
csv.from(process.stdin).on('record', function(data){
    console.log(data[0], "delay", new Date().getTime() - data[1], 'ms' );
});
```

```
$ node producer.js | node consumer.js
```

**Comment by wdavidw** [comment]
doing some house cleaning, closing as this use a very old and depracated api.
