### ISSUE TITLE
Header export of objects

### ISSUE THREAD

**Issue by marklagendijk** [wdavidw/node-csv#171]
When exporting objects to CSV, while including the header in the export, the header will be empty.
E.g.:
``` js
csv()
	.from([
		{ name: 'John Doe' },
		{ name: 'Jane Doe' }
	])
	.to('myData.csv', {
		header: true
	});
	// Result will have no header
```
A workaround is to specify the columns yourself. You can do this dynamically by using `Object.keys`:
``` js
var users = [
	{ name: 'John Doe' },
	{ name: 'Jane Doe' }
];
csv()
	.from(users)
	.to('myData.csv', {
		header: true,
		columns: Object.keys(users[0])
	});
```

**Comment by wdavidw** [comment]
you are using the old API. by looking at the tests, i think [this is fixed with the new one](https://github.com/wdavidw/node-csv-stringify/blob/master/test/header.coffee#L7-L14). please re-open an issue inside the [csv-stringify](https://github.com/wdavidw/node-csv-stringify) project if needed.
