### ISSUE TITLE
stream and Pipe example not working for large csv

### ISSUE THREAD

**Issue by chacliff** [wdavidw/node-csv#194]
I am sending a csv file over post via postman, and the file is obviously getting there. For small csv files this seems to work find but i have an 83MB csv file that i am parsing and transforming into mongodb records and then trying to save them to the database. What appears to be happening though is its storing a large amount of data in memory but not saving it and throwing away what its completed. In Fact when the file is this large its not acting like a true pipe and doing anything with the data. i'll post my two different ways of doing it maybe you can provide me with a solution. 
The Pipe way:

```js
    {
    var input = request.payload.csvFile;
     var parser =csv.parse({delimiter: ','});
     parser.write(input)
     .pipe(transformer)
	.pipe( function(out) {
		console.log("saving");
			if( request.payload.db === "icd10"){ 
				var icd10entry = new ICD10(out); 
					
				icd10entry.save(function(err){
					if(err)console.log("Error saving obj: " + 
					JSON.stringify(out));	
				}); 
					
			}
		}
	); 
}
```

The Stream way: 

```js
{
               'var input = request.payload.csvFile; '
		'var parser =csv.parse({delimiter: ','});'
		'var header =  ""; '
		'//var isFirst = true; '
		'ar transformer = csv.transform( function (data){'
			'console.log("transforming"); '
			'return _.object(header, data); '
		'});'
		parser.on('readable', function(){
			while( record = parser.read()){
				if(isFirst){
					header = record; 
					isFirst = false;
					for(var i in header) { 
						header[i] = toTitleCase(header[i]); 
						header[i] = header[i].replace("-","");
						header[i] = header[i].replace(/ /g, ""); 
					};
					console.log(isFirst); 
					console.log(header); 
				}else {
					console.log("writing");
					transformer.write(record); 
				}
			}
		}); 
		transformer.on('readable', function(){
			var out = transformer.read(); 
			//var icd910entry = new icd9to10(out); 
			//console.log(icd910Entry); 
			 if( request.payload.db === "icd10"){ 
				var icd10entry = new ICD10(out); 
				icd10entry.save(function(err){
					if(err)console.log("Error saving obj: " + 
					JSON.stringify(out));	
				}); 
			}
		});
		parser.write(input);
}
```

sorry if code isn't coming out right it won't cooperate for the preview

**Comment by wdavidw** [comment]
unless i'm mistaken, none of the two are implementation [stream.Transform](https://nodejs.org/api/stream.html)

**Comment by chacliff** [comment]
do you mean my code that i used didn't because following the examples provided both of those methods are indeed using stream.Transform but that is no reason for them not to work here. please reopen this issue.

**Comment by wdavidw** [comment]
i'll reopen but please provides me with a clean test or sample (even if it is a link) with a link to a dataset reproducing the issue.

**Comment by chacliff** [comment]
I have removed all the code from my project and created my own solution using the stream api, i am mainly expressing my concern that these issues aren't actually being handled when their functionality doesn't work as expected.

**Comment by wdavidw** [comment]
most people make the mistake of using transform as a "stream.Readable" while it is a "stream.Transform", meaning it doesnt consume the stream, someone else must do it after. the code u provided cant be reproduced this is why i asked u to send me something usable. closing.

**Comment by chacliff** [comment]
why can't it be repoduced? especially the first one, its a simple pipe example the only item you were missing was the "transformer" which was provided in the 2nd attempt that i made but it was just commented out.  so 



    var input = request.payload.csvFile; 
    var parser =csv.parse({delimiter: ','});
    var header =  ""; 
    var isFirst = true; 
    var transformer = csv.transform( function (data){
         if(isFirst){
              header = data; 
         }
         console.log("transforming"); 
         return _.object(header, data); 
    });
    parser.write(input)
    .pipe(transformer)
    .pipe( function(out) {
        console.log("saving");
            if( request.payload.db === "icd10"){ 
                var icd10entry = new ICD10(out); 

                icd10entry.save(function(err){
                    if(err)console.log("Error saving obj: " + 
                    JSON.stringify(out));   
                }); 

            }
        }
    ); 

ICD10 is an arbitrary mongoose model/schema this could be anything. All it really did was provide a another structure for the document to be sure everything fit into its proper variables for validation. you can substitue icd10entry.save(function()) for ICD10.collection.insert( out). which should be a json object when it gets to that point. 
The point of this post was to show that its clearly not switching reading and writing streams, it is essentially reading the entire file, then transforming and writing it once the read is complete. 
Is this what you were looking for?

**Comment by wdavidw** [comment]
They are few mistakes in your code (again, unless there was new functionnality introduce by 0.12 in the stream API). For example, pipe take a stream.Writable, not a simple function, you are not closing the first stream reader (parser in your example), the condition `isFirst` shall return null and set the variable to "false" if you wish to skip the first header line. Here's a working example:

```
var transformer = csv.transform( function (data){
  // Transform to an object instead of a string
  return data.join(',')+'\n';
});

csv.parse({delimiter: ','})
.pipe(transformer)
.pipe(process.stdout);

parser.write(input)
parser.end();
```

**Comment by chacliff** [comment]
the is first condition was correct when it was written i was just summing it up. 
_.object does create an object in the transform. 
does parser.write(input) not take the buffer and put it into a stream? 
 how big of a file did you use for the above code?
so you specify what the parser and transformer do and then you hand the parser the data and it works? If this is indeed the solution this concept needs to be documented more clearly.

**Comment by wdavidw** [comment]
first condition was correct
> agreed
_.object
> i just remove it for clarity, it doesnt change anything and i did install undescore
parser.write(input)
> it accepts a buffer, this is what i do as well, but this isnt recommanded for a large dataset since you are not streaming data. u shall rather do `rs = getMyStreamReady(); parser = csv.parse(options); rs.pipe(parser).pipe(transformer).pipe(...)`
> you hand the parser the data
yes, the data throttling is handled for you.
> documented more clearly
this is the node.js official [stream api](http://nodejs.org/api/stream.html)

**Comment by chacliff** [comment]
well you've answered all my questions about this issue, i do highly recommend the documentation change for your plugin if you didn't do this already. Thank you

**Comment by wdavidw** [comment]
I encourage you [to participate](https://github.com/wdavidw/node-csv-docs/tree/master/src/documents)
