### ISSUE TITLE
improperly escaped double quotes throw errors

### ISSUE THREAD

**Issue by maxogden** [wdavidw/node-csv#20]
this is technically correct behavior although in practice many CSV parsers are able to correctly parse unescaped double quotes

```
"98174","Permitted Site; undocumented","Lophostemon confertus :: Brisbane Box","2637 24th St","1","Sidewalk: Curb side : Cutout","Tree","Private","","","","3x3","","",""
"98175","Permitted Site; undocumented","Rhaphiolepis "Majestic Beauty" :: Indian Hawthorn  'Majestic Beau'","2637 24th St","2","Sidewalk: Curb side : 
```

the `"Majestic Beauty"` on the second line should instead be `""Majestic Beauty""` but since the double quotes aren't escaped I got an error `Invalid closing quote; found "M" instead of delimiter ","`. it would be nice if this module could try to auto escape double quotes!

**Comment by krunkosaurus** [comment]
+1 Just ran across this today. :)

**Comment by wdavidw** [comment]
doing some house cleaning, closing
