### ISSUE TITLE
Release stable version

### ISSUE THREAD

**Issue by Marsup** [wdavidw/node-csv#200]
Hi,

If you consider this project mature and stable (at least that's what the readme says), why don't  you release a 1.0.0 so we can safely rely on semver ?

**Comment by ngoldman** [comment]
Agree! See https://nodesource.com/blog/semver-tilde-and-caret#1-0-0-anxiety for why it's important to be at v1+ (even better to start there). If there's a patch or minor update, a `~` or `^` won't catch it, so any releases need to be updated manually in any package that depends on this one. Plus:

> It has been tested and used by a large community over the years and should be considered reliable. It provides every option you would expect from an advanced CSV parser and stringifier.

Sounds like 1.0.0+ plus material to me :grin:

**Comment by wdavidw** [comment]
version 1.0.0 released, thanks for your feedbacks

**Comment by Marsup** [comment]
Did you unpublish it or something ? I only see 0.4.6 on npm.

**Comment by ngoldman** [comment]
Confirmed, also only seeing up to 0.4.5 in releases https://github.com/wdavidw/node-csv/releases

:cry:

**Comment by wdavidw** [comment]
"csv-parse" is in version 1.0.0, not "csv". I think the "csv" package could largely be enhanced with goodies functionnalities, this is wait i'll rather wait a bit before transfering it to 1.0.0. However, if this is a problem to you, i not 100% against the idea. What's your opinions?

**Comment by Marsup** [comment]
Unless you plan a major API change like right now, I'd go for 1.0.0. Additions can always go in minor versions.

**Comment by ngoldman** [comment]
+1 @Marsup

Thought we were talking about `node-csv` from the beginning :wink:

**Comment by wdavidw** [comment]
ok csv, csv-generate, csv-parse and csv-stringify are now all at 1.0.0, thanks for your valuable inputs.
