### ISSUE TITLE
Strange behavior of transform: only 16 lines are transformed

### ISSUE THREAD

**Issue by josser** [wdavidw/node-csv#203]
Hi!
Here is a simple example: 

``` javascript
var csv = require('csv');

csv.generate({seed: 1, columns: 2, length: 20})
  .pipe(csv.parse())
  .pipe(csv.transform(function(record){
     console.log(record);
     return record.map(function(value){
       return value.toUpperCase()
     });
  }))
```

Which for some reason logs only 16 items. 
In examples I found almost the same sample of code. (https://github.com/wdavidw/node-csv/blob/master/samples/pipe.js)  The important difference is another .pipe(process.stdout) added to the end

So, it looks like not an issue but something which should be described in docs. 
Can someone please explain why it's required to pipe somewhere after transform stream? 

Thank you, and sorry for my bad english :)

**Comment by wdavidw** [comment]
`csv.transform` respect the Node.js stream.Transform API. Being such, it does not consume a stream reader. This is the reason why `.pipe(process.stdout)` works. You can pass the "consume" option to force it to consume fully the input stream.
