### ISSUE TITLE
Feature Request: Please handle / error when stringify object

### ISSUE THREAD

**Issue by reggi** [wdavidw/node-csv#204]
I was just scratching my head for about 30 minutes because I forgot to wrap the below input object in an array. There's no error / resolve and it really got me. Could save other devs some time in the future. :)

```js
import csv from 'csv'
import Promise from 'bluebird'
Promise.promisifyAll(csv)

let input = [{
  'name': 'thomas'
}]

csv.stringify(input, function(err, output){
  console.log(output)
});

csv.stringifyAsync(input)
.then(console.log)
.catch(console.log.bind(console))
```

**Comment by wdavidw** [comment]
It's quite hard to validate your issue, the signature `stringify {object}, {function}` is valid. In such case, {object} is interpreted as options.

**Comment by reggi** [comment]
@wdavidw What's the point of having options without any data?

**Comment by wdavidw** [comment]
In such case, parse return an stream writer in which you can write or pipe an stream reader. Ser the nodejs stream api and the [./tests/api.coffee](https://github.com/wdavidw/node-csv-parse/blob/master/test/api.coffee)

**Comment by reggi** [comment]
Gotcha @wdavidw I'll just have to put a custom wrapper around it ;)
