### ISSUE TITLE
Small typo on site

### ISSUE THREAD

**Issue by kjs3** [wdavidw/node-csv#205]
I don't see a repo for the documentation site itself but there's a small typo in the `transform` docs.

<img width="895" alt="csv_and_object_transformer___node_js_csv_project" src="https://cloud.githubusercontent.com/assets/91996/12530708/3b2751b6-c1b5-11e5-8f5d-5c361890ac8c.png">

**Comment by wdavidw** [comment]
Documentation is on [github](https://github.com/wdavidw/node-csv-docs). I've fixed it in the source, thanks.

**Comment by kjs3** [comment]
Awesome, thanks!
