### ISSUE TITLE
csv-parser dependency upgrade

### ISSUE THREAD

**Issue by rloehr** [wdavidw/node-csv#206]
Today you upgraded csv-parser to 1.0.5.     This dependency is auto upgraded when using npm.    However, 1.0.5 has a change of functionality in that you now throw errors when encountering a mismatch between header field counts and data field counts.

While the new behavior is correct, for those people depending on a "stable" version of node-csv, there is now a functionality change to contend with forcing them to either adjust their code or fork node-csv and lock down the version number of csv-parser to 1.0.4.

Specifically in our case if you have a csv like:

header1, header2, header3
value1, value2, value3

value4, value5, value6

We had built code around skipping the blank row, but you now throw an error when encountering the blank row stating that the column counts don't match.

**Comment by wdavidw** [comment]
This is being discussed in #74, closing for now, please join the discussion.
