### ISSUE TITLE
make the sync API first-class and deprecate the async API

### ISSUE THREAD

**Issue by jonathanong** [wdavidw/node-csv#207]
i didn't even know there were sync APIs. recommending people to use the async API is misleading because it's not actually async. 

for example: https://github.com/wdavidw/node-csv-parse/blob/4a76f2414fcc0766cd448fb5d2d407811cb914cb/lib/index.js#L45-L48 it's only async because you wrapped it in a `process.nextTick()`. this is something that can be done by the user.

on the other hand, you have a sync API: https://github.com/wdavidw/node-csv-parse/blob/4a76f2414fcc0766cd448fb5d2d407811cb914cb/lib/sync.js which works well

this is similar to issues with templating systems, such as jade, that aren't actually async and thus removed their async API. for templating systems, the only actual async operation are filesystem calls, which can still be sync and cached in production.

really, the only two APIs should be 1) sync and 2) streaming

**Comment by wdavidw** [comment]
Recommended usage is based on stream which is only async, the rest of the api is for conveniency
