### ISSUE TITLE
Need help in parsing a CSV file

### ISSUE THREAD

**Issue by bsurendrakumar** [wdavidw/node-csv#210]
Hi,

I have the following CSV file,

http://jmp.sh/LRtNVxO

After parsing the above file, I need to get the data in the following format,

```json
[{
 "Version" : "0.1"
}, {
"ID": "1",
"Name": "Tom",
"College": "Avanthi",
"City": "Hyderabad",
"Country": "India"
}]
```

I searched on the internet for the solution. But, I did not found anything. Can some one helps with this.

**Comment by wdavidw** [comment]
this is a [csv-parse issue](https://github.com/wdavidw/node-csv-parse). Seems like you need the [column option](https://github.com/wdavidw/node-csv-parse/blob/master/test/columns.coffee)
