### ISSUE TITLE
add / insert and remove columns from csv

### ISSUE THREAD

**Issue by jobe451** [wdavidw/node-csv#213]
I would like to read a csv (with 'columns': true), insert some new columns at a given position and remove some other columns.

I can do most of that by parsing the csv and and then mainpulating the data objects. Hower, inserting a column to a certain position seems not to be possible. Does data objects seem to be plain node-objects. The position of the attribute can not be set, nor is it supposed to be set.

How could I insert columns at a certain position?

**Comment by wdavidw** [comment]
If position is important, you need to output objets as arrays and not objects. Objects in js doesnt garanty order. For ur usecase, I would read csv data with `columns: true`, pipe it to stream-transform to add/remove/order columns and generated an array, and finally pipe the result to csv-stringify or anything else. example:

```coffee
parser = parse options
transformer = transform (record) -> [ record.column_a, record.column_c ]
stringifier = stringify options
fs.createReadStream(path)
.pipe parser
.pipe transformer
.pipe stringifier
.pipe process.stdout
```

**Comment by jobe451** [comment]
This will not solve my use case elegantly, because:
a) I would need to know the names and order of the columns when initiating the stringifier (I want the header to present also in the output file)
b) I would need to know the names and order of the columns for the transform function (I know the names, those are the keys of the data object, but the order is unkown because I can't relay on the object order).

The problem in my case is that I have little knowlege about the input file. The structure might be different every time I process a new file. All I know is, that in there is a column called "A" and I need to upper-case it (my actual use case is a bit more complex). 

The best solution I have so far was to open the csv, read the first record to get to know the header columns. Then process it again, following your suggestion above. Is there anything more elegant (avoiding to open that file twice)?

**Comment by jobe451** [comment]
Implemented as described above by reading the input file twice. Not very efficient, since I can't properly stop the file-read-stream, though.

**Comment by wdavidw** [comment]
could you provide a simple code illustrating your needs. I really dont understand why you couldnt be able to do it dynamically.

**Comment by jobe451** [comment]
Here you go. What is given to me:
- I have receive various csv, with various structure
- I need to perform operations based on column names from the header
- I don't know the position of those columns nor do I know the other columns
- The output must be in the same column order

The script below does perfectly perform the task.

However, transform receives and returns and object. Because of that, the output column order is not guranteed to be equal to the input order, because objects are unorderd.

My current workaround is to process this file twice. First time to get to know the header line. Second time to process it as you suggsted above.

```javascript
"use strict";
var csv = require("csv");

/* ************************************** 
This code reads a random CSV with a header line.

It lowerCases column named in "lowerCaseColumn"

That column may appear at any position of the input-csv

It is required, that the output structure has the same order of fields as the input structure
*/

var lowerCaseColumn = "ColumnMagic";


/* ************************************** */
function generateCSV() {
	var i,j;
	var header="";
	var content="";

	var nrOfColumns = Math.round(Math.random()*5+2);
	var nrOfRows = Math.round(Math.random()*10+2);
	var posOfMagicHeader = Math.floor(Math.random()*nrOfColumns);

	for (i=0; i < nrOfColumns; i++) {
		if(i === posOfMagicHeader)
			header += "ColumnMagic";
		else 
			header += String.fromCharCode(Math.round(Math.random()*20+65));

		if(i + 1 <  nrOfColumns)
			header += ",";
	}
	for (j=0; j < nrOfRows; j++) {
		for (i=0; i < nrOfColumns; i++) {
			content += String.fromCharCode(Math.round(Math.random()*20+65));
			
			if(i + 1 <  nrOfColumns)
				content += ",";
		}
		content += "\n";
	}
	return header + "\n" + content;
}

var parser = csv.parse({delimiter: ",", columns: true});
parser
  .pipe(csv.transform(function(record){
  		record[lowerCaseColumn] = record[lowerCaseColumn].toLowerCase();
		return record;
  }))
  .pipe(csv.stringify ({header: true}))
  .pipe(process.stdout);

parser.write(generateCSV());
```

**Comment by jobe451** [comment]
Thanks for the hint! Yes, you are right, this will basically solve it.
