### ISSUE TITLE
how to parse the chinese csv file

### ISSUE THREAD

**Issue by cephiroth** [wdavidw/node-csv#215]
Use charset 'utf-8' can correctly parse the file.But use charset 'gbk' can't.
How to parse the 'gbk' file?
Thx!

**Comment by cephiroth** [comment]
Correct：
Use charset 'utf-8' can correctly parse the file.But use charset 'ansi' can't.
How to parse the 'gbk' file?
Thx!

**Comment by wdavidw** [comment]
I believed this is a node.js issue. csv doesnt read/write file, only native `fs.readFile`. You may have to convert it to some other encoding before processing.

**Comment by Lutreer** [comment]
Set encoding before reading a file. Such as `reader.readAsText(file, 'utf-8');`
