### ISSUE TITLE
how to import csv to sqlite

### ISSUE THREAD

**Issue by moeinrahimi** [wdavidw/node-csv#217]
hi
can i use this library to import csv files to sqlite ? if yes please give me a guidance .
thanks

**Comment by dguo** [comment]
This is probably too late, but you would use this library to read the CSV data, and then you would use a different library (like [node-sqlite3](https://github.com/mapbox/node-sqlite3) or [node-sqlite](https://github.com/kriasoft/node-sqlite))  to store the data in SQLite.

**Comment by wdavidw** [comment]
Thanks for answering. If you have a large dataset, you'll have to use the stream api, and enclose your sql queries inside something like stream-transform.
