### ISSUE TITLE
Unable to generate CSV using streams

### ISSUE THREAD

**Issue by bsurendrakumar** [wdavidw/node-csv#220]
I'm passing array of objects to stringifier, but stringifier readable event is not at all firing. What I'm doing wrong?

```js
var csv = require('csv');
var data = [{
  'id': 1,
  'name': 'surendra'
}];

var stringifier = csv.stringify({
  header: true
});
stringifier.write(data);
stringifier.on('readable', function () {
  var data;
  while (data = stringifier.read()) {
    process.stdout.write(data);
  }
});
```

**Comment by wdavidw** [comment]
Check the Node.js Stream api or look at the [test cases](https://github.com/wdavidw/node-csv-stringify/blob/master/test/api.write.coffee)
