### ISSUE TITLE
Runtime error with es6 import statement & webpack

### ISSUE THREAD

**Issue by ccsandrew** [wdavidw/node-csv#222]
I would love to use he node csv package in my react application, however I'm getting a strange runtime error.  All I've added is an import statement:

`import * as csv from 'csv';`

Webpack then compiles the application successfully, which indicates that it was happy with the statement and found the module

However, when I run the application in the browser, I get the following error:

>  util.js:103 Uncaught ReferenceError: Buffer is not defined
>     at Object.Buffer (util.js:103)
>     at __webpack_require__ (bootstrap bae1cee…:555)
>     at fn (bootstrap bae1cee…:86)
>     at Object.<anonymous> (_stream_readable.js:37)
>     at Object.<anonymous> (main.js:118663)
>     at __webpack_require__ (bootstrap bae1cee…:555)
>     at fn (bootstrap bae1cee…:86)
>     at Object.module.exports (readable-browser.js:1)
>     at __webpack_require__ (bootstrap bae1cee…:555)
>     at fn (bootstrap bae1cee…:86)

I ought to be able to use your package with Webpack, correct?  Can you help set me straight?

**Comment by wdavidw** [comment]
The package (and its dependencies such as csv-parse or csv-stringify) use Node.js specific dependencies. In fact, it fully respect and implement the Node.js stream API. I believe it would be impossible to use it in a brower environment without rewriting it entirely. But I woud be pleased to be proved the contrary.

**Comment by wdavidw** [comment]
Well, it is possible with a lot of work, maybe in the future.

**Comment by camdagr8** [comment]
Ahh, k... for what it's worth, I did find something else to use: 
https://www.npmjs.com/package/csvtojson
