### ISSUE TITLE
Very slow, clogged at 100% CPU and 25x slower than other parsers

### ISSUE THREAD

**Issue by alexhultman** [wdavidw/node-csv#224]
I'm using this parser to try and stream 20 mb of CSV data into a particular database and I found that the client (Node.js) is using 100% CPU time during this streaming while the database is at 0% CPU. It should be the opposite. The CSV parser is bottlenecking everything and I compared the same CSV file in the standard Golang CSV parser and the diff is 25x in time: 5 seconds vs. 200 ms. Something is seriously bloated in this csv parser and since the readme states this parser is "extremely easy to use and powerful" and lists "Support big datasets" I cannot more than report this.

**Comment by wdavidw** [comment]
Thanks for reporting, i will into the v8 internal to see if sth isnt preventing some js optimization

**Comment by alexhultman** [comment]
I did a search and found about 5 or so similar issue reports that also report very bad performance of this module. Heck one report was about parsing 1 gb of data taking 1 hour - that's completely insane. It should take a couple of milliseconds. Maybe its time to remove those texts about this module being efficient and "powerful" because those texts are not really valid whatsoever.

**Comment by alexhultman** [comment]
Info: csv-parser (https://github.com/mafintosh/csv-parser) is 7x faster than csv-parse (this lib).

**Comment by wdavidw** [comment]
Yes, String.split is faster as well. You have to compare the feature set as well (look at the test cases). But yes, you're right, we could be faster. A better understand of v8 internals would help. I wish I had more time to dig into it. I did a few things in the past few months like removing try/catch but the code could be further optmized.

**Comment by alexhultman** [comment]
A compiler or JIT like V8 is going to try and optimize things like replacing "a / 2" with "a * 0.5" or making "a % 16" into "a & 15" and such. It is never going to "magically optimize" a user written bubble sort into a quicksort. That's not how optimizing passes work. If you want to fix performance you need to look at your own set of function calls and investigate their algorithmical cost. Split, be it in Java, C++ or JavaScript is never a good idea for a parser.
